service: pharmacy

runtime: go112

instance_class: F2
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic  # default value
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 50

handlers:
  - url: /.*
    script: auto
    secure: always

env_variables:
  DB_HOST: /cloudsql/mask-9999:asia-east2:health-insurance-special-pharmacy
  DB_PORT: 5432
  DB_USER: postgres
  DB_PASS: password
  DB: mask